### ISSUE TITLE
Menubar: Print the name of the application in bold

### ISSUE THREAD

**Issue by probonopd** [gnustep/apps-gworkspace#11]
Is it possible to print the name of the application in bold in the menubar?

**Comment by BertrandDekoninck** [comment]
I think this is a GNUstep Gui's issue  (or a Rik's one) because it affects all GNUstep apps when using "NSMenuInterfaceStyle = NSMacintoshInterfaceStyle". You could ask Gui maintainer for this.

**Comment by rmottola** [comment]
This is a theming issue, GWorkspace uses standard menus. Actually, standard GNUstep menu have it in bold. Some themes like ThinkDark or Sonne put it in color too.
