### ISSUE TITLE
GWorkspace won't start when built with PDFKit support

### ISSUE THREAD

**Issue by jasaldivara** [gnustep/apps-gworkspace#12]
I have built and installed PDFKit from https://github.com/gnustep/gap

Then I proceed to build and install GWorkspace:

```
./configure
make -j4
sudo -E make install
```
After installing, I try to open GWorkspace:

```
openapp GWorkspace
```

But it won't start. I only see this message in terminal:

```
Unknown protocol versionzsh: IOT instruction (core dumped)  openapp GWorkspace
```

And immediately terminates.

If I uninstall PDFKit, then uninstall, clean, configure, make and install againt GWorkspace, it opens and works without any issue.

**Comment by rmottola** [comment]
GWorkspace works very well with PDFKit since years on several platforms. you error is very strange.
Which runtime do you use? Which compiler do you use for obj-c? please check that when compiling PDFkit, the C++, C and Obj-C compilers are all configured and detected to be coherent (same clang or gcc version for all and especially no clang/gcc mix)

**Comment by BertrandDekoninck** [comment]
I remember the same problem. Johannes Brakensiek  answered this :
> I’m coming back to this as I’m just updating and fixing the script.
> 
> The errors derives from the old (released) version of PDFKit which misses to link libobjc. If you checkout PDFKit from SVN instead of using the tarball then GWorkspace should run and work:
> 
> svn co http://svn.savannah.nongnu.org/svn/gap/trunk/libs/PDFKit/ <http://svn.savannah.nongnu.org/svn/gap/trunk/libs/PDFKit/>GAP must be out of sync on git.

Bertrand

**Comment by rmottola** [comment]
Oh, perfect. The GAP mirrorring from SVN to GIT is not up-to-date, I'll tell Gregory.
Fine that it is "fixed" and a PDFKit release is due soon with a lot of new features too.
