### ISSUE TITLE
GWorkspace is failing to build

### ISSUE THREAD

**Issue by gcasa** [gnustep/apps-gworkspace#4]
Making all for tool fswatcher...
 Compiling file fswatcher.m ...
 Linking tool fswatcher ...
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSAutoreleasePool'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSMutableData'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSNumber'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSData'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSMutableSet'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSFileHandle'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSMutableDictionary'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSFileManager'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSObject'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSMutableArray'/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSRecursiveLock'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSException'
/usr/GNUstep/System/Library/Libraries/libDBKit.so: error: undefined reference to '__objc_class_name_NSString'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/GNUstep/System/Library/Makefiles/Instance/tool.make:89: recipe for target 'obj/fswatcher' failed
make[5]: *** [obj/fswatcher] Error 1
/usr/GNUstep/System/Library/Makefiles/Instance/tool.make:74: recipe for target 'internal-tool-all_' failed
make[4]: *** [internal-tool-all_] Error 2
/usr/GNUstep/System/Library/Makefiles/Master/rules.make:297: recipe for target 'fswatcher.all.tool.variables' failed
make[3]: *** [fswatcher.all.tool.variables] Error 2
/usr/GNUstep/System/Library/Makefiles/Master/tool.make:71: recipe for target 'internal-all' failed
make[2]: *** [internal-all] Error 2
/usr/GNUstep/System/Library/Makefiles/Master/serial-subdirectories.make:53: recipe for target 'internal-all' failedmake[1]: *** [internal-all] Error 2
/usr/GNUstep/System/Library/Makefiles/Master/serial-subdirectories.make:53: recipe for target 'internal-all' failedmake: *** [internal-all] Error 2
heron@hal-hc-vm apps-gworkspace %

**Comment by rmottola** [comment]
cannot reproduce this on (after an unisntall && make clean of GWorkspace)

- Linux amd64 / gcc and gcc runtime / GWorkspace with metadata enabled
- FreeBSD amd64 / clang lobobjc2 / GWorkspace

You are seeing undefined symbols which should come clearly from base, please clean, check, reconfigure, check your dev envirnoment.
I will do some rebuilds  on other machines and keep an eye on it.

**Comment by gcasa** [comment]
Okay, thanks.  I am going to try again once I get done with day job stuff.

**Comment by rmottola** [comment]
All fine now?

**Comment by gcasa** [comment]
No.  It is still failing occasionally.  It appears that it works from a
fresh gnustep build the first time but building it a second time fails
without any change in environment.

**Comment by gcasa** [comment]
* Do a fresh build of GNUstep... i.e. delete everything under /usr or wherever you have it installed.
* Then build GWorkspace...  it works fine the first time.
* Rebuild it again after doing make distclean
* it FAILS

**Comment by gcasa** [comment]
This is apparently working right now.  I was able to reproduce it but a recent change might have fixed this issue.
