### ISSUE TITLE
Can't compile on Arch Linux

### ISSUE THREAD

**Issue by daemonspudguy** [gnustep/apps-gworkspace#6]
Error code from make is 

> Linking bundle ImageViewer ...
/usr/bin/ld: ./obj/ImageViewer.obj/Resizer.m.o:(.bss+0x0): multiple definition of `serverConnection'; ./obj/ImageViewer.obj/ImageViewer.m.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[6]: *** [/usr/share/GNUstep/Makefiles/Instance/bundle.make:205: ImageViewer.inspector/./ImageViewer] Error 1
make[5]: *** [/usr/share/GNUstep/Makefiles/Instance/bundle.make:193: internal-bundle-run-compile-submake] Error 2
make[4]: *** [/usr/share/GNUstep/Makefiles/Master/rules.make:297: ImageViewer.all.bundle.variables] Error 2
make[3]: *** [/usr/share/GNUstep/Makefiles/Master/bundle.make:37: internal-all] Error 2
make[2]: *** [/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
make[1]: *** [/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2
make: *** [/usr/share/GNUstep/Makefiles/Master/serial-subdirectories.make:53: internal-all] Error 2

**Comment by fengdlm** [comment]
I have the same issue.

**Comment by fengdlm** [comment]
Comment out `#import "Resizer.h"` in Inspector/ContentViewers/ImageViewer/ImageViewer.m solved the compilation problem for me.

**Comment by rmottola** [comment]
I don't get this issue on Linux, I also think the error is bogus, I see no redefinition of serverConnection.
Are you using release or latest git HEAD?
It should have been fixed by: https://github.com/gnustep/apps-gworkspace/commit/ea0f7fef5efd798a8bcad59d20fe48eb4232d730

**Comment by hipocentrum** [comment]
I can compile latest from master branch, Arch Linux
gnustep-base 1.28.0
gnustep-make 2.9.0
gnustep-back 0.29.0
gnustep-gui 0.29.0
gcc-objc 11.1.0

**Comment by daemonspudguy** [comment]
This is from last year, I have since switched to Gentoo.

**Comment by rmottola** [comment]
Several of my main GNUstep development systems run Gentoo... so rest assured it is well tested (with gcc runtime though!)
