### ISSUE TITLE
Menubar: Space between the icon and the text

### ISSUE THREAD

**Issue by probonopd** [gnustep/apps-gworkspace#7]
Can the space between the icon and the text be increased?

![image](https://user-images.githubusercontent.com/2480569/93721423-b8ea4280-fb7f-11ea-91e8-96643d56a983.png)

**Comment by rmottola** [comment]
This is a theme issue, not a GWorkspace issue. That specific theme is using an icon a little too big and does not adjust drawing. File a bug to the specifc theme you are using.
