### ISSUE TITLE
Move Dock to the bottom of the screen

### ISSUE THREAD

**Issue by probonopd** [gnustep/apps-gworkspace#9]
The Dock in GWorkspace seemingly cannot be moved to the bottom of the screen.
Is there a hidden setting somewhere?

Reference:
https://github.com/furybsd/furybsd-livecd/issues/189#issuecomment-695825093

**Comment by rmottola** [comment]
No, there is no hidden setting. At the bottom it would interfere with either the Tabbed Shelf and/or WindowMaker's icons.

**Comment by probonopd** [comment]
> Tabbed Shelf and/or WindowMaker's icons.

...things "modern" Mac users don't understand nor use. But I respect your decision to target pre-Apple NeXT UX.

**Comment by rmottola** [comment]
There is a world beyond Mac users... and Mac users might also try something new, for the good or the bad! It is not that difficult to understand and play with. WindowMaker Icons are in fact very similar to Apple's Dock, just more flexible and in a different presentation.
Apple is not the only think to be inspired from especially after "Big Sur". GNUstep and GWorkspace try to take the best of worlds
